version: '3.8'

services:
  lottie-api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production